name: AET
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=24.0
  - gym=0.21.0
  - patchelf
  - pip:
    - setuptools==65.5.0
    - wheel==0.37.1
    - absl-py
    - aiohttp
    - aiosignal
    - async-timeout
    - attrs
    - beautifulsoup4
    - boto3
    - botocore
    - cachetools
    - cffi
    - charset-normalizer
    - click
    - cloudpickle
    - configargparse
    - cycler
    - cython==0.29.32
    - d4rl
    - dm-control
    - dm-env
    - dm-tree
    - docker-pycreds
    - fasteners
    - filelock
    - fonttools
    - frozenlist
    - fsspec
    - future
    - gdown
    - gitdb
    - gitpython
    - glfw
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - h5py
    - huggingface-hub
    - idna
    - imageio
    - jmespath
    - joblib
    - kiwisolver
    - labmaze
    - lxml
    - markdown
    - markupsafe
    - matplotlib
    - mujoco==2.2.1
    - mujoco-py==2.1.2.14
    - multidict
    - numpy==1.24.1
    - oauthlib
    - pandas
    - pathtools
    - pillow
    - promise
    - protobuf
    - pyasn1
    - pyasn1-modules
    - pycparser
    - pydeprecate
    - pyglet
    - pyopengl
    - pyparsing
    - pysocks
    - pytorch-lightning
    - pytorch-transformers
    - pytz
    - pyyaml
    - regex
    - requests
    - requests-oauthlib
    - rsa
    - s3transfer
    - sacremoses
    - scikit-learn
    - scipy
    - seaborn
    - sentencepiece
    - sentry-sdk
    - setproctitle
    - shortuuid
    - smmap
    - soupsieve
    - stable-baselines3==1.2.0
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - termcolor
    - threadpoolctl
    - tokenizers
    - torch==2.4.0
    - torchvision==0.19.0
    - torchaudio==2.4.0
    - tqdm
    - transformers
    - typing-extensions
    - urllib3
    - wandb
    - werkzeug
    - yarl
    - "git+https://github.com/aravindr93/mjrl@master#egg=mjrl"
    # - "git+https://github.com/aviralkumar2907/rlkit-offline-rl-benchmark.git"